export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FORGOT_PASSWORD: '/forgot-password',
  VERIFY_OTP: '/verify-otp',
  RESET_PASSWORD: '/reset-password',
  DASHBOARD: '/dashboard',
  JOBS: '/jobs',
  PROFILE: '/profile',
  RESUMES: '/resumes',
  APPLICATIONS: '/applications',
} as const;

export const AUTH_STRINGS = {
  LOGIN_TITLE: 'Welcome Back 👋',
  LOGIN_SUBTITLE: "Don't have an account?",
  LOGIN_LINK: 'Sign up for free',
  LOGIN_BUTTON: 'Sign In',
  SIGNUP_TITLE: 'Create Account',
  SIGNUP_SUBTITLE: 'Already have an account?',
  SIGNUP_LINK: 'Sign in',
  SIGNUP_BUTTON: 'Create Account',
  FORGOT_TITLE: 'Forgot Password?',
  FORGOT_SUBTITLE: 'Enter your email and we\'ll send you a reset code.',
  FORGOT_BUTTON: 'Send Reset Code',
  EMAIL_LABEL: 'Email Address',
  PASSWORD_LABEL: 'Password',
  CONFIRM_PASSWORD_LABEL: 'Confirm Password',
  REMEMBER_ME: 'Remember me',
  FORGOT_LINK: 'Forgot password?',
  OR_CONTINUE: 'or continue with',
  REQUIRED: '*',
} as const;
